env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    impliedStrict: true
  ecmaVersion: 2018
rules: {
  comma-dangle: ["error", "always-multiline"]
}
